spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: xedice2003
    url: jdbc:postgresql://localhost:5432/express
  jpa:
    show-sql: true

    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect